### ISSUE TITLE
Looks like launchEditor is missing 

### ISSUE THREAD

**Issue by bartmoc** [tfga/pidginCli#1]
I'm getting this error after running the command:
```
➜  pidginCli git:(master) ✗ echo 'hi' | pidginMsg xxxxxxx@gmail.com
Traceback (most recent call last):
  File "/usr/local/bin/pidginMsg", line 6, in <module>
    from PidginCli.Main import entryPoint
  File "/usr/local/lib/python2.7/dist-packages/PidginCli/Main.py", line 5, in <module>
    from tfga.launchEditor import launchEditor
```
Looks like launchEditor is missing

**Comment by tfga** [comment]
Hi, @bartmoc,

Thanks for letting me know.

I just fixed this, I think. Could you check if everything is ok now? Just update the repo and install again:

```sh
git pull
pip2 install .
```

I also updated the documentation. If you have any comments, they're wellcome. :)
