### ISSUE TITLE
Does not work on Fedora32 with python3.8

### ISSUE THREAD

**Issue by wernermaes** [tfga/pidginCli#3]
Hello

It is possible to make it work on Fedora32 and python3.8?

**Comment by tfga** [comment]
Hi,

I don't use Fedora. Can you send more information? (Error messages? Stack
traces?)

**Comment by wernermaes** [comment]
Hello

I  made it work.
Will post the details here in a minute

**Comment by wernermaes** [comment]
python3 print is a function, so  it should use print("hello") instead of print "hello"
also I needed to change the install script to use python3 (since I don't have dbus module in python2.7). Fedora32 install python3-dbus

in install script:

   virtualenv --clear -p python3 --system-site-packages .venv

created file /pidginCli/.venv/lib/python3.8/site-packages/PidginCli/ArgParser.py

    print (args)

created file     /pidginCli/.venv/lib/python3.8/site-packages/PidginCli/pidginCli.py

    elif lenAccounts > 1:

        print ('WARNING: More than one account found. Using the first one.')

        for a in accounts:

            print ('a, purple.PurpleAccountGetUsername(a)')

**Comment by tfga** [comment]
Thanks for the feedback.

What is the actual command line for installing `python3-dbus` on Fedora? I'm updating README.

If I created a branch with your modifications, would you be willing to test it before I merge it into master?

Did you run into any other issues?

**Comment by wernermaes** [comment]
@tfga 

dnf install python3-dbus is the command.
I'm willing to test it.
For the moment I only tried sending a message to several users, which worked fine.

Kind regards

**Comment by tfga** [comment]
@wernermaes 

Great! :smile: 

Here the branch: [Fedora32](https://github.com/tfga/pidginCli/tree/Fedora32).

I modified `README`, `install` and the python code. If you could go through the installation procedure once again (when you have the time, ofc) and let me know how it went, it would be great. :+1:
